name: Code Quality

on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [ 8.3, 8.4 ]
        os: [ ubuntu-latest ]
        year: [ 2015, 2018, 2019, 2020, 2021, 2022, 2023, 2024 ]

    name: Unit Tests for Year ${{ matrix.year }} (PHP ${{ matrix.php }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, intl

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Run tests
        run: vendor/bin/phpunit ${{ matrix.year }}
