name: Tests

on:
  push: ~
  pull_request: ~

jobs:
  phpunit:
    name: PHPUnit on ${{ matrix.php }} ${{ matrix.composer-flags }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4']
        coverage: [true]
        composer-flags: ['']
        include:
          - php: '8.0'
            coverage: false
            composer-flags: '--ignore-platform-req=php'
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: curl, mbstring
          coverage: pcov
          tools: composer:v2
      - name: "Use PHPUnit 9.5+ on PHP 8"
        run: composer require --no-update --dev phpunit/phpunit:^9.5
        if: "matrix.php == '8.0'"
      - run: composer update --no-progress ${{ matrix.composer-flags }}
      - run: vendor/bin/phpunit 2015
      - run: vendor/bin/phpunit 2020
